swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /order:
    get:
      operationId: order.read_all
      tags:
        - Order
      responses:
        200:
          description: Successfully
          schema:
            type: array
            items:
              properties:
                order_id:
                  type: string
                  description: Id
                latitude:
                  type: string
                  description: latitude
                longitude:
                  type: string
                  description: longitude
                timestamp:
                  type: string
                  description: Creation/Update timestamp

    post:
      operationId: order.create
      tags:
        - Order
      parameters:
        - name: order
          in: body
          description: Order to create
          required: True
          schema:
            type: object
            properties:
              latitude:
                type: string
                description: latitude
              longitude:
                type: string
                description: longitude
      responses:
        201:
          description: Successfully created
          schema:
            properties:
              order_id:
                type: string
                description: Id
              latitude:
                type: string
                description: latitude
              longitude:
                type: string
                description: longitude
              timestamp:
                type: string
                description: Creation/Update timestamp

  /order/{order_id}:
    get:
      operationId: order.read_one
      tags:
        - Order
      parameters:
        - name: order_id
          in: path
          description: Id to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read
          schema:
            type: object
            properties:
              order_id:
                type: string
                description: Id
              latitude:
                type: string
                description: latitude
              longitude:
                type: string
                description: longitude
              timestamp:
                type: string
                description: Creation/Update timestamp

    put:
      operationId: order.update
      tags:
        - Order
      parameters:
        - name: order_id
          in: path
          description: Id to update
          type: integer
          required: True
        - name: order
          in: body
          schema:
            type: object
            properties:
              latitude:
                type: string
                description: latitude
              longitude:
                type: string
                description: longitude
      responses:
        200:
          description: Successfully updated
          schema:
            properties:
              order_id:
                type: string
                description: Id in the database
              latitude:
                type: string
                description: latitude
              longitude:
                type: string
                description: longitude
              timestamp:
                type: string
                description: Creation/Update timestamp

    delete:
      operationId: order.delete
      tags:
        - Order
      parameters:
        - name: order_id
          in: path
          type: integer
          description: Id
          required: true
      responses:
        200:
          description: Successfully deleted

  /order_plan:
    get:
      operationId: order_plan.read_all
      tags:
        - order_plan
      responses:
        200:
          description: Successfully
          schema:
            type: array
            items:
              properties:
                order_plan_id:
                  type: string
                  description: Id
                paths:
                  type: string
                  description: paths

    post:
      operationId: order_plan.create
      tags:
        - order_plan
      parameters:
        - name: order_plan
          in: body
          description: Order to create
          required: True
          schema:
            type: object
            properties:
              paths:
                type: string
                description: paths
      responses:
        201:
          description: Successfully created
          schema:
            properties:
              order_plan_id:
                type: string
                description: Id
              paths:
                type: string
                description: paths
  /order_plan/{order_plan_id}:
    get:
      operationId: order_plan.read_one
      tags:
        - order_plan
      parameters:
        - name: order_plan_id
          in: path
          description: Id to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read
          schema:
            type: object
            properties:
              order_plan_id:
                type: string
                description: Id
              paths:
                type: string
                description: paths


    put:
      operationId: order_plan.update
      tags:
        - order_plan
      parameters:
        - name: order_plan_id
          in: path
          description: Id to update
          type: integer
          required: True
        - name: order
          in: body
          schema:
            type: object
            properties:
              paths:
                type: string
                description: path
      responses:
        200:
          description: Successfully updated
          schema:
            properties:
              order_plan_id:
                type: string
                description: Id in the database
              paths:
                type: string
                description: paths

    delete:
      operationId: order_plan.delete
      tags:
        - order_plan
      parameters:
        - name: order_plan_id
          in: path
          type: integer
          description: Id
          required: true
      responses:
        200:
          description: Successfully deleted
  /give_path/{order_plan_id}:
    get:
      operationId: order_plan.get_path
      tags:
        - order_plan
      parameters:
        - name: order_plan_id
          in: path
          description: Id to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read
          schema:
            type: object
            properties:
              path:
                type: array
                description: path